export const files = [
  {
    id: 1,
    fileNumber: 'F-2024-001',
    clientId: 1,
    rcUserId: 1,
    employeeFirstName: 'James',
    employeeLastName: 'Anderson',
    employeeEmail: 'james.anderson@techcorp.com',
    employeePhone: '(555) 111-2222',
    isVip: true,
    originCity: 'New York',
    originState: 'NY',
    originCountry: 'USA',
    destinationCity: 'San Francisco',
    destinationState: 'CA',
    destinationCountry: 'USA',
    authorizationDate: '2024-01-15',
    estimatedPackDate: '2025-02-01',
    estimatedLoadDate: '2025-02-02',
    estimatedDeliveryDate: '2025-02-10',
    estimatedFinalMoveDate: '2025-02-15',
    actualPackDate: null,
    actualLoadDate: null,
    actualDeliveryDate: null,
    actualFinalMoveDate: null,
    homeSaleStartDate: '2024-12-01',
    homeSaleCloseDate: null,
    homeSalePrice: null,
    totalAllowance: 75000,
    expensesToDate: 12500,
    fileStatus: 'active'
  },
  {
    id: 2,
    fileNumber: 'F-2024-002',
    clientId: 2,
    rcUserId: 1,
    employeeFirstName: 'Maria',
    employeeLastName: 'Garcia',
    employeeEmail: 'maria.garcia@globalfinance.com',
    employeePhone: '(555) 222-3333',
    isVip: false,
    originCity: 'Chicago',
    originState: 'IL',
    originCountry: 'USA',
    destinationCity: 'Austin',
    destinationState: 'TX',
    destinationCountry: 'USA',
    authorizationDate: '2024-02-01',
    estimatedPackDate: '2025-01-20',
    estimatedLoadDate: '2025-01-21',
    estimatedDeliveryDate: '2025-01-25',
    estimatedFinalMoveDate: '2025-01-28',
    actualPackDate: null,
    actualLoadDate: null,
    actualDeliveryDate: null,
    actualFinalMoveDate: null,
    homeSaleStartDate: null,
    homeSaleCloseDate: null,
    homeSalePrice: null,
    totalAllowance: 45000,
    expensesToDate: 8900,
    fileStatus: 'active'
  },
  {
    id: 3,
    fileNumber: 'F-2024-003',
    clientId: 1,
    rcUserId: 2,
    employeeFirstName: 'Robert',
    employeeLastName: 'Kim',
    employeeEmail: 'robert.kim@techcorp.com',
    employeePhone: '(555) 333-4444',
    isVip: false,
    originCity: 'Boston',
    originState: 'MA',
    originCountry: 'USA',
    destinationCity: 'Seattle',
    destinationState: 'WA',
    destinationCountry: 'USA',
    authorizationDate: '2024-01-20',
    estimatedPackDate: '2025-01-15',
    estimatedLoadDate: '2025-01-16',
    estimatedDeliveryDate: '2025-01-22',
    estimatedFinalMoveDate: '2025-01-25',
    actualPackDate: null,
    actualLoadDate: null,
    actualDeliveryDate: null,
    actualFinalMoveDate: null,
    homeSaleStartDate: '2024-11-15',
    homeSaleCloseDate: '2025-01-10',
    homeSalePrice: 525000,
    totalAllowance: 50000,
    expensesToDate: 28000,
    fileStatus: 'active'
  },
  {
    id: 4,
    fileNumber: 'F-2024-004',
    clientId: 3,
    rcUserId: 1,
    employeeFirstName: 'Linda',
    employeeLastName: 'Johnson',
    employeeEmail: 'linda.johnson@healthcare.com',
    employeePhone: '(555) 444-5555',
    isVip: true,
    originCity: 'Miami',
    originState: 'FL',
    originCountry: 'USA',
    destinationCity: 'Denver',
    destinationState: 'CO',
    destinationCountry: 'USA',
    authorizationDate: '2024-01-10',
    estimatedPackDate: '2024-12-28',
    estimatedLoadDate: '2024-12-29',
    estimatedDeliveryDate: '2025-01-05',
    estimatedFinalMoveDate: '2025-01-10',
    actualPackDate: '2024-12-28',
    actualLoadDate: '2024-12-29',
    actualDeliveryDate: '2025-01-06',
    actualFinalMoveDate: null,
    homeSaleStartDate: '2024-10-01',
    homeSaleCloseDate: '2024-12-15',
    homeSalePrice: 425000,
    totalAllowance: 65000,
    expensesToDate: 52000,
    fileStatus: 'active'
  },
  {
    id: 5,
    fileNumber: 'F-2024-005',
    clientId: 4,
    rcUserId: 3,
    employeeFirstName: 'David',
    employeeLastName: 'Miller',
    employeeEmail: 'david.miller@manufacturing.com',
    employeePhone: '(555) 555-6666',
    isVip: false,
    originCity: 'Detroit',
    originState: 'MI',
    originCountry: 'USA',
    destinationCity: 'Charlotte',
    destinationState: 'NC',
    destinationCountry: 'USA',
    authorizationDate: '2024-02-15',
    estimatedPackDate: '2025-03-10',
    estimatedLoadDate: '2025-03-11',
    estimatedDeliveryDate: '2025-03-15',
    estimatedFinalMoveDate: '2025-03-20',
    actualPackDate: null,
    actualLoadDate: null,
    actualDeliveryDate: null,
    actualFinalMoveDate: null,
    homeSaleStartDate: null,
    homeSaleCloseDate: null,
    homeSalePrice: null,
    totalAllowance: 38000,
    expensesToDate: 5200,
    fileStatus: 'active'
  },
  {
    id: 6,
    fileNumber: 'F-2024-006',
    clientId: 2,
    rcUserId: 1,
    employeeFirstName: 'Patricia',
    employeeLastName: 'Brown',
    employeeEmail: 'patricia.brown@globalfinance.com',
    employeePhone: '(555) 666-7777',
    isVip: false,
    originCity: 'Atlanta',
    originState: 'GA',
    originCountry: 'USA',
    destinationCity: 'Portland',
    destinationState: 'OR',
    destinationCountry: 'USA',
    authorizationDate: '2024-01-25',
    estimatedPackDate: '2025-01-18',
    estimatedLoadDate: '2025-01-19',
    estimatedDeliveryDate: '2025-01-26',
    estimatedFinalMoveDate: '2025-01-30',
    actualPackDate: null,
    actualLoadDate: null,
    actualDeliveryDate: null,
    actualFinalMoveDate: null,
    homeSaleStartDate: '2024-11-01',
    homeSaleCloseDate: null,
    homeSalePrice: null,
    totalAllowance: 42000,
    expensesToDate: 15000,
    fileStatus: 'active'
  },
  {
    id: 7,
    fileNumber: 'F-2023-089',
    clientId: 1,
    rcUserId: 2,
    employeeFirstName: 'Thomas',
    employeeLastName: 'Wilson',
    employeeEmail: 'thomas.wilson@techcorp.com',
    employeePhone: '(555) 777-8888',
    isVip: false,
    originCity: 'Phoenix',
    originState: 'AZ',
    originCountry: 'USA',
    destinationCity: 'Philadelphia',
    destinationState: 'PA',
    destinationCountry: 'USA',
    authorizationDate: '2023-11-01',
    estimatedPackDate: '2024-12-10',
    estimatedLoadDate: '2024-12-11',
    estimatedDeliveryDate: '2024-12-18',
    estimatedFinalMoveDate: '2024-12-22',
    actualPackDate: '2024-12-10',
    actualLoadDate: '2024-12-11',
    actualDeliveryDate: '2024-12-17',
    actualFinalMoveDate: '2024-12-20',
    homeSaleStartDate: '2023-10-01',
    homeSaleCloseDate: '2024-11-30',
    homeSalePrice: 385000,
    totalAllowance: 48000,
    expensesToDate: 47500,
    fileStatus: 'completed'
  },
  {
    id: 8,
    fileNumber: 'F-2024-007',
    clientId: 5,
    rcUserId: 4,
    employeeFirstName: 'Jennifer',
    employeeLastName: 'Davis',
    employeeEmail: 'jennifer.davis@retail.com',
    employeePhone: '(555) 888-9999',
    isVip: true,
    originCity: 'Houston',
    originState: 'TX',
    originCountry: 'USA',
    destinationCity: 'Nashville',
    destinationState: 'TN',
    destinationCountry: 'USA',
    authorizationDate: '2024-02-01',
    estimatedPackDate: '2025-02-25',
    estimatedLoadDate: '2025-02-26',
    estimatedDeliveryDate: '2025-03-01',
    estimatedFinalMoveDate: '2025-03-05',
    actualPackDate: null,
    actualLoadDate: null,
    actualDeliveryDate: null,
    actualFinalMoveDate: null,
    homeSaleStartDate: '2024-12-10',
    homeSaleCloseDate: null,
    homeSalePrice: null,
    totalAllowance: 55000,
    expensesToDate: 8200,
    fileStatus: 'active'
  },
  {
    id: 9,
    fileNumber: 'F-2024-008',
    clientId: 3,
    rcUserId: 5,
    employeeFirstName: 'Michael',
    employeeLastName: 'Taylor',
    employeeEmail: 'michael.taylor@healthcare.com',
    employeePhone: '(555) 999-0000',
    isVip: false,
    originCity: 'San Diego',
    originState: 'CA',
    originCountry: 'USA',
    destinationCity: 'Minneapolis',
    destinationState: 'MN',
    destinationCountry: 'USA',
    authorizationDate: '2024-01-18',
    estimatedPackDate: '2025-01-25',
    estimatedLoadDate: '2025-01-26',
    estimatedDeliveryDate: '2025-02-02',
    estimatedFinalMoveDate: '2025-02-06',
    actualPackDate: null,
    actualLoadDate: null,
    actualDeliveryDate: null,
    actualFinalMoveDate: null,
    homeSaleStartDate: null,
    homeSaleCloseDate: null,
    homeSalePrice: null,
    totalAllowance: 40000,
    expensesToDate: 12000,
    fileStatus: 'active'
  },
  {
    id: 10,
    fileNumber: 'F-2024-009',
    clientId: 4,
    rcUserId: 1,
    employeeFirstName: 'Susan',
    employeeLastName: 'Martinez',
    employeeEmail: 'susan.martinez@manufacturing.com',
    employeePhone: '(555) 000-1111',
    isVip: false,
    originCity: 'Columbus',
    originState: 'OH',
    originCountry: 'USA',
    destinationCity: 'Raleigh',
    destinationState: 'NC',
    destinationCountry: 'USA',
    authorizationDate: '2024-02-10',
    estimatedPackDate: '2025-03-15',
    estimatedLoadDate: '2025-03-16',
    estimatedDeliveryDate: '2025-03-20',
    estimatedFinalMoveDate: '2025-03-25',
    actualPackDate: null,
    actualLoadDate: null,
    actualDeliveryDate: null,
    actualFinalMoveDate: null,
    homeSaleStartDate: '2024-12-20',
    homeSaleCloseDate: null,
    homeSalePrice: null,
    totalAllowance: 35000,
    expensesToDate: 4500,
    fileStatus: 'active'
  },
  {
    id: 11,
    fileNumber: 'F-2024-010',
    clientId: 1,
    rcUserId: 1,
    employeeFirstName: 'Christopher',
    employeeLastName: 'Lee',
    employeeEmail: 'chris.lee@techcorp.com',
    employeePhone: '(555) 111-3333',
    isVip: true,
    originCity: 'Los Angeles',
    originState: 'CA',
    originCountry: 'USA',
    destinationCity: 'Boston',
    destinationState: 'MA',
    destinationCountry: 'USA',
    authorizationDate: '2024-01-05',
    estimatedPackDate: '2024-12-20',
    estimatedLoadDate: '2024-12-21',
    estimatedDeliveryDate: '2024-12-28',
    estimatedFinalMoveDate: '2025-01-02',
    actualPackDate: '2024-12-20',
    actualLoadDate: '2024-12-21',
    actualDeliveryDate: '2024-12-27',
    actualFinalMoveDate: null,
    homeSaleStartDate: '2024-09-15',
    homeSaleCloseDate: '2024-11-20',
    homeSalePrice: 1250000,
    totalAllowance: 80000,
    expensesToDate: 68000,
    fileStatus: 'active'
  },
  {
    id: 12,
    fileNumber: 'F-2024-011',
    clientId: 2,
    rcUserId: 3,
    employeeFirstName: 'Amanda',
    employeeLastName: 'White',
    employeeEmail: 'amanda.white@globalfinance.com',
    employeePhone: '(555) 222-4444',
    isVip: false,
    originCity: 'Dallas',
    originState: 'TX',
    originCountry: 'USA',
    destinationCity: 'Tampa',
    destinationState: 'FL',
    destinationCountry: 'USA',
    authorizationDate: '2024-02-05',
    estimatedPackDate: '2025-02-20',
    estimatedLoadDate: '2025-02-21',
    estimatedDeliveryDate: '2025-02-25',
    estimatedFinalMoveDate: '2025-03-01',
    actualPackDate: null,
    actualLoadDate: null,
    actualDeliveryDate: null,
    actualFinalMoveDate: null,
    homeSaleStartDate: null,
    homeSaleCloseDate: null,
    homeSalePrice: null,
    totalAllowance: 43000,
    expensesToDate: 7800,
    fileStatus: 'active'
  }
]
