export const taskRules = [
  {
    id: 1,
    taskName: 'Confirm Final Move Date',
    taskText: 'Contact employee to confirm final move date is still accurate, 7 days prior to scheduled date.',
    sqlTriggerLogic: "CURRENT_DATE = (estimated_final_move_date - INTERVAL '7 days')::DATE AND estimated_final_move_date IS NOT NULL AND file_status = 'active'",
    triggerType: 'date_based',
    service: 'household_goods',
    subservice: 'move_coordination',
    taskType: 'call',
    applicableClients: null, // null = all clients
    applicableFileStatuses: ['active'],
    tiedLetterTemplateId: null,
    dueDateOffsetDays: 0,
    priority: 'high',
    isRecurring: false,
    recurrenceIntervalDays: null,
    isActive: true
  },
  {
    id: 2,
    taskName: 'Pre-Pack Call',
    taskText: 'Contact employee 3 days before pack date to confirm readiness and answer questions.',
    sqlTriggerLogic: "CURRENT_DATE = (estimated_pack_date - INTERVAL '3 days')::DATE AND estimated_pack_date IS NOT NULL AND file_status = 'active'",
    triggerType: 'date_based',
    service: 'household_goods',
    subservice: 'packing',
    taskType: 'call',
    applicableClients: null,
    applicableFileStatuses: ['active'],
    tiedLetterTemplateId: null,
    dueDateOffsetDays: 0,
    priority: 'high',
    isRecurring: false,
    recurrenceIntervalDays: null,
    isActive: true
  },
  {
    id: 3,
    taskName: 'Confirm Delivery Date',
    taskText: 'Contact employee to confirm delivery date and provide carrier contact information.',
    sqlTriggerLogic: "CURRENT_DATE = (estimated_delivery_date - INTERVAL '5 days')::DATE AND estimated_delivery_date IS NOT NULL AND file_status = 'active'",
    triggerType: 'date_based',
    service: 'household_goods',
    subservice: 'delivery',
    taskType: 'email',
    applicableClients: null,
    applicableFileStatuses: ['active'],
    tiedLetterTemplateId: 1,
    dueDateOffsetDays: 0,
    priority: 'high',
    isRecurring: false,
    recurrenceIntervalDays: null,
    isActive: true
  },
  {
    id: 4,
    taskName: 'Expense Allowance Warning',
    taskText: 'Employee has used 80% of total allowance. Contact to discuss remaining expenses and budget.',
    sqlTriggerLogic: "expenses_to_date > (total_allowance * 0.8) AND file_status = 'active'",
    triggerType: 'event_based',
    service: 'expense_management',
    subservice: 'budget_tracking',
    taskType: 'call',
    applicableClients: null,
    applicableFileStatuses: ['active'],
    tiedLetterTemplateId: null,
    dueDateOffsetDays: 1,
    priority: 'urgent',
    isRecurring: false,
    recurrenceIntervalDays: null,
    isActive: true
  },
  {
    id: 5,
    taskName: 'Home Sale Follow-up',
    taskText: 'Follow up on home sale progress. No closing date set after 60 days on market.',
    sqlTriggerLogic: "home_sale_start_date IS NOT NULL AND home_sale_close_date IS NULL AND CURRENT_DATE > (home_sale_start_date + INTERVAL '60 days') AND file_status = 'active'",
    triggerType: 'date_based',
    service: 'home_sale',
    subservice: 'listing_management',
    taskType: 'call',
    applicableClients: null,
    applicableFileStatuses: ['active'],
    tiedLetterTemplateId: null,
    dueDateOffsetDays: 0,
    priority: 'urgent',
    isRecurring: false,
    recurrenceIntervalDays: null,
    isActive: true
  },
  {
    id: 6,
    taskName: 'Title Company Coordination',
    taskText: 'Contact title company to ensure closing documents are ready.',
    sqlTriggerLogic: "CURRENT_DATE = (home_sale_close_date - INTERVAL '3 days')::DATE AND home_sale_close_date IS NOT NULL AND file_status = 'active'",
    triggerType: 'date_based',
    service: 'home_sale',
    subservice: 'closing',
    taskType: 'call',
    applicableClients: null,
    applicableFileStatuses: ['active'],
    tiedLetterTemplateId: null,
    dueDateOffsetDays: 0,
    priority: 'high',
    isRecurring: false,
    recurrenceIntervalDays: null,
    isActive: true
  },
  {
    id: 7,
    taskName: 'Submit Storage Voucher',
    taskText: 'Create and submit voucher for storage facility charges.',
    sqlTriggerLogic: "storage_start_date IS NOT NULL AND CURRENT_DATE >= (storage_start_date + INTERVAL '30 days') AND file_status = 'active'",
    triggerType: 'date_based',
    service: 'household_goods',
    subservice: 'storage',
    taskType: 'voucher',
    applicableClients: null,
    applicableFileStatuses: ['active'],
    tiedLetterTemplateId: null,
    dueDateOffsetDays: 0,
    priority: 'normal',
    isRecurring: true,
    recurrenceIntervalDays: 30,
    isActive: true
  },
  {
    id: 8,
    taskName: 'Home Finding Services Introduction',
    taskText: 'Introduce employee to destination services coordinator for home search.',
    sqlTriggerLogic: "CURRENT_DATE = (estimated_pack_date - INTERVAL '45 days')::DATE AND estimated_pack_date IS NOT NULL AND file_status = 'active'",
    triggerType: 'date_based',
    service: 'destination_services',
    subservice: 'home_finding',
    taskType: 'email',
    applicableClients: null,
    applicableFileStatuses: ['active'],
    tiedLetterTemplateId: 4,
    dueDateOffsetDays: 0,
    priority: 'normal',
    isRecurring: false,
    recurrenceIntervalDays: null,
    isActive: true
  },
  {
    id: 9,
    taskName: 'VIP Move Coordination Letter',
    taskText: 'Send VIP move coordination letter with white-glove service details.',
    sqlTriggerLogic: "is_vip = true AND CURRENT_DATE = (estimated_pack_date - INTERVAL '10 days')::DATE AND estimated_pack_date IS NOT NULL AND file_status = 'active'",
    triggerType: 'date_based',
    service: 'household_goods',
    subservice: 'move_coordination',
    taskType: 'letter',
    applicableClients: null,
    applicableFileStatuses: ['active'],
    tiedLetterTemplateId: 3,
    dueDateOffsetDays: 0,
    priority: 'high',
    isRecurring: false,
    recurrenceIntervalDays: null,
    isActive: true
  },
  {
    id: 10,
    taskName: 'Final Expense Reconciliation',
    taskText: 'Review and reconcile all move-related expenses before file closure.',
    sqlTriggerLogic: "CURRENT_DATE = (actual_final_move_date + INTERVAL '7 days')::DATE AND actual_final_move_date IS NOT NULL AND file_status = 'active'",
    triggerType: 'date_based',
    service: 'expense_management',
    subservice: 'reconciliation',
    taskType: 'call',
    applicableClients: null,
    applicableFileStatuses: ['active'],
    tiedLetterTemplateId: null,
    dueDateOffsetDays: 0,
    priority: 'high',
    isRecurring: false,
    recurrenceIntervalDays: null,
    isActive: true
  },
  {
    id: 11,
    taskName: 'Post-Move Survey',
    taskText: 'Send post-move satisfaction survey to gather feedback on relocation experience.',
    sqlTriggerLogic: "CURRENT_DATE = (actual_final_move_date + INTERVAL '14 days')::DATE AND actual_final_move_date IS NOT NULL",
    triggerType: 'date_based',
    service: 'quality_assurance',
    subservice: 'feedback',
    taskType: 'email',
    applicableClients: null,
    applicableFileStatuses: ['active', 'completed'],
    tiedLetterTemplateId: 7,
    dueDateOffsetDays: 0,
    priority: 'low',
    isRecurring: false,
    recurrenceIntervalDays: null,
    isActive: true
  },
  {
    id: 12,
    taskName: 'Loss/Damage Claim Follow-up',
    taskText: 'Follow up on household goods loss/damage claim with carrier.',
    sqlTriggerLogic: "claim_filed = true AND claim_status = 'pending' AND CURRENT_DATE > (claim_filed_date + INTERVAL '14 days') AND file_status = 'active'",
    triggerType: 'event_based',
    service: 'household_goods',
    subservice: 'claims',
    taskType: 'call',
    applicableClients: null,
    applicableFileStatuses: ['active'],
    tiedLetterTemplateId: null,
    dueDateOffsetDays: 0,
    priority: 'high',
    isRecurring: false,
    recurrenceIntervalDays: null,
    isActive: true
  },
  // Inactive rule for testing
  {
    id: 13,
    taskName: 'Old Rule - Deactivated',
    taskText: 'This rule is no longer in use.',
    sqlTriggerLogic: "file_status = 'active'",
    triggerType: 'event_based',
    service: 'general',
    subservice: 'misc',
    taskType: 'call',
    applicableClients: [1, 2],
    applicableFileStatuses: ['active'],
    tiedLetterTemplateId: null,
    dueDateOffsetDays: 0,
    priority: 'low',
    isRecurring: false,
    recurrenceIntervalDays: null,
    isActive: false
  }
]
