export const tasks = [
  // Overdue tasks
  {
    id: 1,
    ruleId: 1,
    taskName: 'Confirm Final Move Date',
    taskText: 'Contact employee to confirm final move date is still accurate, 7 days prior to scheduled date.',
    service: 'household_goods',
    subservice: 'move_coordination',
    taskType: 'call',
    priority: 'high',
    fileId: 4,
    vendorId: null,
    tiedLetterTemplateId: null,
    dueDate: '2025-01-03',
    firstAttemptDate: null,
    completedDate: null,
    status: 'active',
    assignedToUserId: 1
  },
  {
    id: 2,
    ruleId: 5,
    taskName: 'Home Sale Follow-up',
    taskText: 'Follow up on home sale progress. No closing date set after 60 days on market.',
    service: 'home_sale',
    subservice: 'listing_management',
    taskType: 'call',
    priority: 'urgent',
    fileId: 6,
    vendorId: 3,
    tiedLetterTemplateId: null,
    dueDate: '2024-12-30',
    firstAttemptDate: '2024-12-30T10:30:00',
    completedDate: null,
    status: 'in_progress',
    assignedToUserId: 1
  },

  // Due today
  {
    id: 3,
    ruleId: 2,
    taskName: 'Pre-Pack Call',
    taskText: 'Contact employee 3 days before pack date to confirm readiness and answer questions.',
    service: 'household_goods',
    subservice: 'packing',
    taskType: 'call',
    priority: 'high',
    fileId: 2,
    vendorId: 1,
    tiedLetterTemplateId: null,
    dueDate: '2025-01-17',
    firstAttemptDate: null,
    completedDate: null,
    status: 'active',
    assignedToUserId: 1
  },
  {
    id: 4,
    ruleId: null, // Manual task
    taskName: 'Send Welcome Package',
    taskText: 'Send destination city welcome package and area information to employee.',
    service: 'destination_services',
    subservice: 'area_orientation',
    taskType: 'email',
    priority: 'normal',
    fileId: 1,
    vendorId: 9,
    tiedLetterTemplateId: 2,
    dueDate: '2025-01-17',
    firstAttemptDate: null,
    completedDate: null,
    status: 'active',
    assignedToUserId: 1
  },
  {
    id: 5,
    ruleId: 7,
    taskName: 'Submit Storage Voucher',
    taskText: 'Create and submit voucher for storage facility charges.',
    service: 'household_goods',
    subservice: 'storage',
    taskType: 'voucher',
    priority: 'normal',
    fileId: 3,
    vendorId: 5,
    tiedLetterTemplateId: null,
    dueDate: '2025-01-17',
    firstAttemptDate: null,
    completedDate: null,
    status: 'active',
    assignedToUserId: 2
  },

  // Due this week
  {
    id: 6,
    ruleId: 3,
    taskName: 'Confirm Delivery Date',
    taskText: 'Contact employee to confirm delivery date and provide carrier contact information.',
    service: 'household_goods',
    subservice: 'delivery',
    taskType: 'email',
    priority: 'high',
    fileId: 4,
    vendorId: 2,
    tiedLetterTemplateId: 1,
    dueDate: '2025-01-18',
    firstAttemptDate: null,
    completedDate: null,
    status: 'active',
    assignedToUserId: 1
  },
  {
    id: 7,
    ruleId: 4,
    taskName: 'Expense Allowance Warning',
    taskText: 'Employee has used 80% of total allowance. Contact to discuss remaining expenses and budget.',
    service: 'expense_management',
    subservice: 'budget_tracking',
    taskType: 'call',
    priority: 'urgent',
    fileId: 4,
    vendorId: null,
    tiedLetterTemplateId: null,
    dueDate: '2025-01-18',
    firstAttemptDate: null,
    completedDate: null,
    status: 'active',
    assignedToUserId: 1
  },
  {
    id: 8,
    ruleId: 6,
    taskName: 'Title Company Coordination',
    taskText: 'Contact title company to ensure closing documents are ready.',
    service: 'home_sale',
    subservice: 'closing',
    taskType: 'call',
    priority: 'high',
    fileId: 3,
    vendorId: 10,
    tiedLetterTemplateId: null,
    dueDate: '2025-01-19',
    firstAttemptDate: null,
    completedDate: null,
    status: 'active',
    assignedToUserId: 2
  },
  {
    id: 9,
    ruleId: 1,
    taskName: 'Confirm Final Move Date',
    taskText: 'Contact employee to confirm final move date is still accurate, 7 days prior to scheduled date.',
    service: 'household_goods',
    subservice: 'move_coordination',
    taskType: 'call',
    priority: 'high',
    fileId: 2,
    vendorId: null,
    tiedLetterTemplateId: null,
    dueDate: '2025-01-21',
    firstAttemptDate: null,
    completedDate: null,
    status: 'active',
    assignedToUserId: 1
  },
  {
    id: 10,
    ruleId: null,
    taskName: 'Temp Housing Check-in',
    taskText: 'Follow up with employee on temporary housing satisfaction and address any issues.',
    service: 'temp_housing',
    subservice: 'occupancy',
    taskType: 'call',
    priority: 'normal',
    fileId: 1,
    vendorId: 6,
    tiedLetterTemplateId: null,
    dueDate: '2025-01-20',
    firstAttemptDate: null,
    completedDate: null,
    status: 'active',
    assignedToUserId: 1
  },
  {
    id: 11,
    ruleId: 9,
    taskName: 'VIP Move Coordination Letter',
    taskText: 'Send VIP move coordination letter with white-glove service details.',
    service: 'household_goods',
    subservice: 'move_coordination',
    taskType: 'letter',
    priority: 'high',
    fileId: 1,
    vendorId: null,
    tiedLetterTemplateId: 3,
    dueDate: '2025-01-22',
    firstAttemptDate: null,
    completedDate: null,
    status: 'active',
    assignedToUserId: 1
  },

  // Due next week
  {
    id: 12,
    ruleId: 2,
    taskName: 'Pre-Pack Call',
    taskText: 'Contact employee 3 days before pack date to confirm readiness and answer questions.',
    service: 'household_goods',
    subservice: 'packing',
    taskType: 'call',
    priority: 'high',
    fileId: 9,
    vendorId: 1,
    tiedLetterTemplateId: null,
    dueDate: '2025-01-22',
    firstAttemptDate: null,
    completedDate: null,
    status: 'active',
    assignedToUserId: 5
  },
  {
    id: 13,
    ruleId: null,
    taskName: 'Auto Transport Scheduling',
    taskText: 'Coordinate vehicle pickup date with auto transport vendor.',
    service: 'auto_transport',
    subservice: 'scheduling',
    taskType: 'email',
    priority: 'normal',
    fileId: 2,
    vendorId: 8,
    tiedLetterTemplateId: null,
    dueDate: '2025-01-23',
    firstAttemptDate: null,
    completedDate: null,
    status: 'active',
    assignedToUserId: 1
  },
  {
    id: 14,
    ruleId: 8,
    taskName: 'Home Finding Services Introduction',
    taskText: 'Introduce employee to destination services coordinator for home search.',
    service: 'destination_services',
    subservice: 'home_finding',
    taskType: 'email',
    priority: 'normal',
    fileId: 5,
    vendorId: 9,
    tiedLetterTemplateId: 4,
    dueDate: '2025-01-24',
    firstAttemptDate: null,
    completedDate: null,
    status: 'active',
    assignedToUserId: 3
  },
  {
    id: 15,
    ruleId: null,
    taskName: 'Moving Company Voucher',
    taskText: 'Process payment voucher for moving company services.',
    service: 'household_goods',
    subservice: 'moving',
    taskType: 'voucher',
    priority: 'normal',
    fileId: 11,
    vendorId: 2,
    tiedLetterTemplateId: null,
    dueDate: '2025-01-24',
    firstAttemptDate: null,
    completedDate: null,
    status: 'active',
    assignedToUserId: 1
  },

  // Due later
  {
    id: 16,
    ruleId: 1,
    taskName: 'Confirm Final Move Date',
    taskText: 'Contact employee to confirm final move date is still accurate, 7 days prior to scheduled date.',
    service: 'household_goods',
    subservice: 'move_coordination',
    taskType: 'call',
    priority: 'high',
    fileId: 8,
    vendorId: null,
    tiedLetterTemplateId: null,
    dueDate: '2025-02-26',
    firstAttemptDate: null,
    completedDate: null,
    status: 'active',
    assignedToUserId: 4
  },
  {
    id: 17,
    ruleId: 2,
    taskName: 'Pre-Pack Call',
    taskText: 'Contact employee 3 days before pack date to confirm readiness and answer questions.',
    service: 'household_goods',
    subservice: 'packing',
    taskType: 'call',
    priority: 'high',
    fileId: 1,
    vendorId: 1,
    tiedLetterTemplateId: null,
    dueDate: '2025-01-29',
    firstAttemptDate: null,
    completedDate: null,
    status: 'active',
    assignedToUserId: 1
  },
  {
    id: 18,
    ruleId: null,
    taskName: 'Destination Area Tour Coordination',
    taskText: 'Schedule destination area tour for employee and family.',
    service: 'destination_services',
    subservice: 'area_orientation',
    taskType: 'call',
    priority: 'low',
    fileId: 5,
    vendorId: 9,
    tiedLetterTemplateId: null,
    dueDate: '2025-02-15',
    firstAttemptDate: null,
    completedDate: null,
    status: 'active',
    assignedToUserId: 3
  },
  {
    id: 19,
    ruleId: 2,
    taskName: 'Pre-Pack Call',
    taskText: 'Contact employee 3 days before pack date to confirm readiness and answer questions.',
    service: 'household_goods',
    subservice: 'packing',
    taskType: 'call',
    priority: 'high',
    fileId: 12,
    vendorId: 1,
    tiedLetterTemplateId: null,
    dueDate: '2025-02-17',
    firstAttemptDate: null,
    completedDate: null,
    status: 'active',
    assignedToUserId: 3
  },
  {
    id: 20,
    ruleId: 8,
    taskName: 'Home Finding Services Introduction',
    taskText: 'Introduce employee to destination services coordinator for home search.',
    service: 'destination_services',
    subservice: 'home_finding',
    taskType: 'email',
    priority: 'normal',
    fileId: 10,
    vendorId: 9,
    tiedLetterTemplateId: 4,
    dueDate: '2025-02-28',
    firstAttemptDate: null,
    completedDate: null,
    status: 'active',
    assignedToUserId: 1
  },

  // Completed tasks
  {
    id: 21,
    ruleId: 2,
    taskName: 'Pre-Pack Call',
    taskText: 'Contact employee 3 days before pack date to confirm readiness and answer questions.',
    service: 'household_goods',
    subservice: 'packing',
    taskType: 'call',
    priority: 'high',
    fileId: 4,
    vendorId: 1,
    tiedLetterTemplateId: null,
    dueDate: '2024-12-25',
    firstAttemptDate: '2024-12-25T09:15:00',
    completedDate: '2024-12-25T09:30:00',
    status: 'completed',
    assignedToUserId: 1
  },
  {
    id: 22,
    ruleId: 3,
    taskName: 'Confirm Delivery Date',
    taskText: 'Contact employee to confirm delivery date and provide carrier contact information.',
    service: 'household_goods',
    subservice: 'delivery',
    taskType: 'email',
    priority: 'high',
    fileId: 4,
    vendorId: 2,
    tiedLetterTemplateId: 1,
    dueDate: '2024-12-28',
    firstAttemptDate: '2024-12-27T14:20:00',
    completedDate: '2024-12-27T14:25:00',
    status: 'completed',
    assignedToUserId: 1
  },
  {
    id: 23,
    ruleId: 1,
    taskName: 'Confirm Final Move Date',
    taskText: 'Contact employee to confirm final move date is still accurate, 7 days prior to scheduled date.',
    service: 'household_goods',
    subservice: 'move_coordination',
    taskType: 'call',
    priority: 'high',
    fileId: 3,
    vendorId: null,
    tiedLetterTemplateId: null,
    dueDate: '2025-01-15',
    firstAttemptDate: '2025-01-15T11:00:00',
    completedDate: '2025-01-15T11:15:00',
    status: 'completed',
    assignedToUserId: 2
  },
  {
    id: 24,
    ruleId: 6,
    taskName: 'Title Company Coordination',
    taskText: 'Contact title company to ensure closing documents are ready.',
    service: 'home_sale',
    subservice: 'closing',
    taskType: 'call',
    priority: 'high',
    fileId: 3,
    vendorId: 10,
    tiedLetterTemplateId: null,
    dueDate: '2025-01-08',
    firstAttemptDate: '2025-01-08T10:00:00',
    completedDate: '2025-01-08T10:20:00',
    status: 'completed',
    assignedToUserId: 2
  },
  {
    id: 25,
    ruleId: 2,
    taskName: 'Pre-Pack Call',
    taskText: 'Contact employee 3 days before pack date to confirm readiness and answer questions.',
    service: 'household_goods',
    subservice: 'packing',
    taskType: 'call',
    priority: 'high',
    fileId: 11,
    vendorId: 1,
    tiedLetterTemplateId: null,
    dueDate: '2024-12-17',
    firstAttemptDate: '2024-12-17T13:30:00',
    completedDate: '2024-12-17T13:45:00',
    status: 'completed',
    assignedToUserId: 1
  },
  {
    id: 26,
    ruleId: 3,
    taskName: 'Confirm Delivery Date',
    taskText: 'Contact employee to confirm delivery date and provide carrier contact information.',
    service: 'household_goods',
    subservice: 'delivery',
    taskType: 'email',
    priority: 'high',
    fileId: 11,
    vendorId: 2,
    tiedLetterTemplateId: 1,
    dueDate: '2024-12-20',
    firstAttemptDate: '2024-12-20T08:00:00',
    completedDate: '2024-12-20T08:10:00',
    status: 'completed',
    assignedToUserId: 1
  },
  {
    id: 27,
    ruleId: 9,
    taskName: 'VIP Move Coordination Letter',
    taskText: 'Send VIP move coordination letter with white-glove service details.',
    service: 'household_goods',
    subservice: 'move_coordination',
    taskType: 'letter',
    priority: 'high',
    fileId: 11,
    vendorId: null,
    tiedLetterTemplateId: 3,
    dueDate: '2024-12-15',
    firstAttemptDate: '2024-12-14T16:00:00',
    completedDate: '2024-12-14T16:15:00',
    status: 'completed',
    assignedToUserId: 1
  },
  {
    id: 28,
    ruleId: null,
    taskName: 'Initial Consultation Call',
    taskText: 'Welcome call to explain relocation process and benefits.',
    service: 'general',
    subservice: 'onboarding',
    taskType: 'call',
    priority: 'high',
    fileId: 1,
    vendorId: null,
    tiedLetterTemplateId: null,
    dueDate: '2025-01-10',
    firstAttemptDate: '2025-01-10T10:00:00',
    completedDate: '2025-01-10T10:30:00',
    status: 'completed',
    assignedToUserId: 1
  },

  // Cancelled tasks
  {
    id: 29,
    ruleId: null,
    taskName: 'Schedule House Hunting Trip',
    taskText: 'Coordinate house hunting trip dates and accommodations.',
    service: 'destination_services',
    subservice: 'home_finding',
    taskType: 'call',
    priority: 'normal',
    fileId: 3,
    vendorId: 9,
    tiedLetterTemplateId: null,
    dueDate: '2024-12-10',
    firstAttemptDate: '2024-12-08T14:00:00',
    completedDate: null,
    status: 'cancelled',
    assignedToUserId: 2
  },
  {
    id: 30,
    ruleId: 7,
    taskName: 'Submit Storage Voucher',
    taskText: 'Create and submit voucher for storage facility charges.',
    service: 'household_goods',
    subservice: 'storage',
    taskType: 'voucher',
    priority: 'normal',
    fileId: 7,
    vendorId: 5,
    tiedLetterTemplateId: null,
    dueDate: '2024-12-15',
    firstAttemptDate: null,
    completedDate: null,
    status: 'cancelled',
    assignedToUserId: 2
  },

  // More active tasks for variety
  {
    id: 31,
    ruleId: null,
    taskName: 'Rental Assistance Coordination',
    taskText: 'Connect employee with rental assistance program details.',
    service: 'destination_services',
    subservice: 'rental_assistance',
    taskType: 'email',
    priority: 'low',
    fileId: 6,
    vendorId: null,
    tiedLetterTemplateId: 5,
    dueDate: '2025-01-28',
    firstAttemptDate: null,
    completedDate: null,
    status: 'active',
    assignedToUserId: 1
  },
  {
    id: 32,
    ruleId: null,
    taskName: 'Spouse Career Services Introduction',
    taskText: 'Introduce spouse to career transition services and job search resources.',
    service: 'spouse_support',
    subservice: 'career_services',
    taskType: 'call',
    priority: 'normal',
    fileId: 1,
    vendorId: null,
    tiedLetterTemplateId: null,
    dueDate: '2025-01-25',
    firstAttemptDate: null,
    completedDate: null,
    status: 'active',
    assignedToUserId: 1
  },
  {
    id: 33,
    ruleId: null,
    taskName: 'School Enrollment Assistance',
    taskText: 'Provide school enrollment information and district contacts for destination area.',
    service: 'destination_services',
    subservice: 'school_search',
    taskType: 'email',
    priority: 'high',
    fileId: 8,
    vendorId: 9,
    tiedLetterTemplateId: 6,
    dueDate: '2025-02-01',
    firstAttemptDate: null,
    completedDate: null,
    status: 'active',
    assignedToUserId: 4
  },
  {
    id: 34,
    ruleId: 10,
    taskName: 'Final Expense Reconciliation',
    taskText: 'Review and reconcile all move-related expenses before file closure.',
    service: 'expense_management',
    subservice: 'reconciliation',
    taskType: 'call',
    priority: 'high',
    fileId: 11,
    vendorId: null,
    tiedLetterTemplateId: null,
    dueDate: '2025-01-30',
    firstAttemptDate: null,
    completedDate: null,
    status: 'active',
    assignedToUserId: 1
  },
  {
    id: 35,
    ruleId: 11,
    taskName: 'Post-Move Survey',
    taskText: 'Send post-move satisfaction survey to gather feedback on relocation experience.',
    service: 'quality_assurance',
    subservice: 'feedback',
    taskType: 'email',
    priority: 'low',
    fileId: 7,
    vendorId: null,
    tiedLetterTemplateId: 7,
    dueDate: '2025-01-05',
    firstAttemptDate: null,
    completedDate: null,
    status: 'active',
    assignedToUserId: 2
  },
  {
    id: 36,
    ruleId: null,
    taskName: 'Temp Housing Extension Request',
    taskText: 'Process request for temporary housing extension due to home purchase delay.',
    service: 'temp_housing',
    subservice: 'extensions',
    taskType: 'call',
    priority: 'urgent',
    fileId: 6,
    vendorId: 6,
    tiedLetterTemplateId: null,
    dueDate: '2025-01-18',
    firstAttemptDate: null,
    completedDate: null,
    status: 'active',
    assignedToUserId: 1
  },
  {
    id: 37,
    ruleId: 12,
    taskName: 'Loss/Damage Claim Follow-up',
    taskText: 'Follow up on household goods loss/damage claim with carrier.',
    service: 'household_goods',
    subservice: 'claims',
    taskType: 'call',
    priority: 'high',
    fileId: 4,
    vendorId: 2,
    tiedLetterTemplateId: null,
    dueDate: '2025-01-20',
    firstAttemptDate: '2025-01-16T11:00:00',
    completedDate: null,
    status: 'in_progress',
    assignedToUserId: 1
  },
  {
    id: 38,
    ruleId: null,
    taskName: 'Cultural Training Coordination',
    taskText: 'Coordinate international cultural training for international assignment.',
    service: 'international_services',
    subservice: 'cultural_training',
    taskType: 'email',
    priority: 'normal',
    fileId: 12,
    vendorId: null,
    tiedLetterTemplateId: null,
    dueDate: '2025-02-10',
    firstAttemptDate: null,
    completedDate: null,
    status: 'active',
    assignedToUserId: 3
  },
  {
    id: 39,
    ruleId: null,
    taskName: 'Utilities Setup Assistance',
    taskText: 'Provide utility company contacts and assistance for destination home setup.',
    service: 'destination_services',
    subservice: 'settling_in',
    taskType: 'email',
    priority: 'normal',
    fileId: 9,
    vendorId: null,
    tiedLetterTemplateId: 8,
    dueDate: '2025-01-27',
    firstAttemptDate: null,
    completedDate: null,
    status: 'active',
    assignedToUserId: 5
  },
  {
    id: 40,
    ruleId: null,
    taskName: 'Pet Relocation Coordination',
    taskText: 'Coordinate pet relocation services and veterinary record transfers.',
    service: 'specialty_services',
    subservice: 'pet_relocation',
    taskType: 'call',
    priority: 'normal',
    fileId: 5,
    vendorId: null,
    tiedLetterTemplateId: null,
    dueDate: '2025-02-20',
    firstAttemptDate: null,
    completedDate: null,
    status: 'active',
    assignedToUserId: 3
  }
]
